Add ctest definitions for cloudsc variants
ecmwf-ifs/dwarf-p-cloudsc pull request #18
Opened 2022-08-31 12:18 UTC by reuterbal

Compiler vendor devtechs like to do a simple `ctest` after building the dwarf to check stuff works as expected. This adds a few sanity tests to the CMake to facilitate that.

Used the opportunity to also apply the CMake cleanup to the classic Fortran variants, which have somehow evaded that change...

2022-09-19 13:29 UTC, mlange05 requested changes
Ok, this is looking really great, many thanks! The few issues I had with this are not showstoppers, so I'm marking this as "changes requested", but these should be trivial, and/or could be disabled/bypassed if needed.

The key ones are to force the CUDA_HEAPSIZE flag for both SCC variants, and somehow disabling the CLAW GPU runs (which seem to be broken in develop already).

I've also had trouble running the MPI ones behind `srun`, and I'm not sure if there is a good solution to pass additional arguments via flags to customise. If I've missed something obvious, a README entry might be nice to point those out. However, please ignore if this is cumbersome.

2022-09-19 13:29 UTC, mlange05 commented on src/cloudsc_loki/CMakeLists.txt
> +        OMP 1
Same as with the standalone GPU version; "NVCOMPILER_ACC_CUDA_HEAPSIZE=64M" fixes it.

2022-09-20 08:40 UTC, reuterbal commented on src/cloudsc_gpu/CMakeLists.txt
> +        OMP 1
Very good point and should be there indeed! I tend to export this and then forget about it...

2022-09-20 08:41 UTC, reuterbal commented on src/cloudsc_fortran/CMakeLists.txt
> -    target_include_directories(dwarf-cloudsc-fortran PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/../common)
Well, the clean-up was in my yard, so ...

2022-09-20 08:41 UTC, reuterbal commented on src/cloudsc_gpu/CMakeLists.txt
> +        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/../../..
I'll see which way it works or if it can be resolved - otherwise I'll remove this test until fixed

2022-09-20 14:25 UTC, reuterbal commented
Thanks for the helpful comments and tests! Indeed, the environment configuration was missing from the SCC tests.
I'm not sure what is wrong with the CLAW variant but wasn't able to fix it ad-hoc. This should be done in a separate PR I think and I have marked the test as ENABLED=OFF in the meantime.

ecbuild [looks for](https://github.com/ecmwf/ecbuild/blob/develop/cmake/ecbuild_add_test.cmake#L204) `mpiexec mpirun lamexec srun` (in that order) and which of those work seems to be dependent on the environment. On Atos, mpiexec is found and working fine, however, then serial runs of MPI-enabled builds fail without `srun -n1`, or similar, but work fine if built without MPI. With CMake variable `MPIEXEC_EXECUTABLE` the launcher can be overwritten but since this seems so highly environment-dependent, I'm not sure I'd attempt to get this working in every instance or even describe this for something like CLOUDSC.

2022-09-20 14:26 UTC, reuterbal commented
PS: I had to piggy-back some fixes for the Github workflow, where CMake seems to have unearthed a GFortran 12 compiler in the runner image which isn't officially documented and doesn't seem to have a libm....

2022-10-04 04:44 UTC, mlange05 approved these changes
Excellent, many thanks! Works nicely now on multiple systems.

2022-10-04 04:46 UTC, merged