CLOUDSC SCC-CUDA-C (semi-automatic) implementations
ecmwf-ifs/dwarf-p-cloudsc pull request #40
Opened 2023-02-20 15:55 UTC by MichaelSt98

Build with `--cloudsc-cuda`.

3 versions implemented: 

* **SCC-CUDA-C** - SCC-CUDA implementation (`nlev`/`klev` to be a parameter)
* **SCC-CUDA-C-HOIST** - host side hoisted temporary local arrays 
* **SCC-CUDA-C-K-CACHING** - combination of loop fusion and local temporary array demotion

_____

expected results:

SCC-CUDA-C

```
bin/dwarf-cloudsc-cuda 1 262144 128
     NUMOMP=1, NGPTOT=262144, NPROMA=128, NGPBLKS=2048
     NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s
          1    262144    262144         0       128    0 :         83    389970 @ core#
          1    262144    262144      2048       128   -1 :       2401     13623 TOTAL
             Variable Dim             MinValue             MaxValue            AbsMaxErr         AvgAbsErr/GP          MaxRelErr-%
                PLUDE 2D1  0.0000000000000e+00  1.0267201089823e-04  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
             PCOVPTOT 2D3  0.0000000000000e+00  1.0000000000000e+00  3.6637359812630e-15  1.0209399286330e-15  3.8311567725177e-15      
     PRAINFRAC_TOPRFZ 2D1  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFSQLF 2D3 -2.5817563600963e-06  4.0808628024869e-06  1.5396809049817e-19  2.5084851673472e-19  2.4634086684021e-12  !!!!
               PFSQIF 2D3 -2.8108738214051e-06  3.8878365981669e-06  1.7639461126571e-19  2.2367462786190e-19  9.9816470294425e-13  !!!!
              PFCQLNG 2D1 -3.5555642908082e-08  1.4133894678714e-09  3.3087224502121e-24  4.2309994566325e-24  0.0000000000000e+00      
              PFCQNNG 2D1 -5.2850140216625e-07  8.7885623295760e-09  5.2939559203394e-23  2.3127969379217e-23  0.0000000000000e+00      
               PFSQRF 2D3 -2.5817563600963e-06  4.0808628024869e-06  1.5396809049817e-19  2.4104192014749e-19  2.4926179583640e-12  !!!!
               PFSQSF 2D3 -2.7688769863077e-06  3.8603498954962e-06  1.8528845721188e-19  2.2185613820860e-19  9.9577244421460e-13  !!!!
              PFCQRNG 2D1 -3.5555642908082e-08  1.4133894678714e-09  3.3087224502121e-24  4.0294350860824e-24  0.0000000000000e+00      
              PFCQSNG 2D1 -5.2850140216625e-07  8.7885623295760e-09  5.2939559203394e-23  2.1069493041057e-23  0.0000000000000e+00      
             PFSQLTUR 2D1 -8.1159493430619e-07  2.6534563852270e-07  1.0587911840679e-22  3.4886441373701e-23  0.0000000000000e+00      
             PFSQITUR 2D1 -2.6516903010901e-06  3.8645677692316e-07  2.1175823681358e-22  1.2054745469441e-22  0.0000000000000e+00      
               PFPLSL 2D1  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFPLSN 2D3  0.0000000000000e+00  2.9699580041076e-05  2.8460307027744e-19  3.7566047890832e-19  2.1693813127696e-13      
               PFHPSL 2D1 -0.0000000000000e+00 -0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFHPSN 2D3 -8.4183459626431e+01 -0.0000000000000e+00  8.0646600508771e-13  1.0643881949166e-12  2.1685227105686e-13      
       TENDENCY_LOC%A 2D3 -2.7777777777778e-04  2.6313098096235e-04  8.4025668367627e-18  1.1848310181127e-18  2.5955723722741e-13  !!!!
       TENDENCY_LOC%Q 2D1 -1.9973824048511e-08  1.4955800737964e-08  1.7470054537120e-21  7.2807391164265e-22  0.0000000000000e+00      
       TENDENCY_LOC%T 2D3 -4.1322003941667e-05  5.4352784463613e-05  4.9195673576530e-18  2.3261971677214e-18  1.0467742587122e-12  !!!!
     TENDENCY_LOC%CLD 2D1 -1.2224810361478e-08  9.8165463509733e-09  7.7739467943499e-22  3.7345209871079e-22  0.0000000000000e+00  
```

SCC-CUDA-C-HOIST

```
bin/dwarf-cloudsc-cuda-hoist 1 262144 128
     NUMOMP=1, NGPTOT=262144, NPROMA=128, NGPBLKS=2048
     NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s
          1    262144    262144         0       128    0 :         87    372947 @ core#
          1    262144    262144      2048       128   -1 :       2400     13629 TOTAL
             Variable Dim             MinValue             MaxValue            AbsMaxErr         AvgAbsErr/GP          MaxRelErr-%
                PLUDE 2D1  0.0000000000000e+00  1.0267201089823e-04  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
             PCOVPTOT 2D3  0.0000000000000e+00  1.0000000000000e+00  3.6637359812630e-15  1.0209399286330e-15  3.8311567725177e-15      
     PRAINFRAC_TOPRFZ 2D1  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFSQLF 2D3 -2.5817563600963e-06  4.0808628024869e-06  1.5396809049817e-19  2.5084851673472e-19  2.4634086684021e-12  !!!!
               PFSQIF 2D3 -2.8108738214051e-06  3.8878365981669e-06  1.7639461126571e-19  2.2367462786190e-19  9.9816470294425e-13  !!!!
              PFCQLNG 2D1 -3.5555642908082e-08  1.4133894678714e-09  3.3087224502121e-24  4.2309994566325e-24  0.0000000000000e+00      
              PFCQNNG 2D1 -5.2850140216625e-07  8.7885623295760e-09  5.2939559203394e-23  2.3127969379217e-23  0.0000000000000e+00      
               PFSQRF 2D3 -2.5817563600963e-06  4.0808628024869e-06  1.5396809049817e-19  2.4104192014749e-19  2.4926179583640e-12  !!!!
               PFSQSF 2D3 -2.7688769863077e-06  3.8603498954962e-06  1.8528845721188e-19  2.2185613820860e-19  9.9577244421460e-13  !!!!
              PFCQRNG 2D1 -3.5555642908082e-08  1.4133894678714e-09  3.3087224502121e-24  4.0294350860824e-24  0.0000000000000e+00      
              PFCQSNG 2D1 -5.2850140216625e-07  8.7885623295760e-09  5.2939559203394e-23  2.1069493041057e-23  0.0000000000000e+00      
             PFSQLTUR 2D1 -8.1159493430619e-07  2.6534563852270e-07  1.0587911840679e-22  3.4886441373701e-23  0.0000000000000e+00      
             PFSQITUR 2D1 -2.6516903010901e-06  3.8645677692316e-07  2.1175823681358e-22  1.2054745469441e-22  0.0000000000000e+00      
               PFPLSL 2D1  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFPLSN 2D3  0.0000000000000e+00  2.9699580041076e-05  2.8460307027744e-19  3.7566047890832e-19  2.1693813127696e-13      
               PFHPSL 2D1 -0.0000000000000e+00 -0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
               PFHPSN 2D3 -8.4183459626431e+01 -0.0000000000000e+00  8.0646600508771e-13  1.0643881949166e-12  2.1685227105686e-13      
       TENDENCY_LOC%A 2D3 -2.7777777777778e-04  2.6313098096235e-04  8.4025668367627e-18  1.1848310181127e-18  2.5955723722741e-13  !!!!
       TENDENCY_LOC%Q 2D1 -1.9973824048511e-08  1.4955800737964e-08  1.7470054537120e-21  7.2807391164265e-22  0.0000000000000e+00      
       TENDENCY_LOC%T 2D3 -4.1322003941667e-05  5.4352784463613e-05  4.9195673576530e-18  2.3261971677214e-18  1.0467742587122e-12  !!!!
     TENDENCY_LOC%CLD 2D1 -1.2224810361478e-08  9.8165463509733e-09  7.7739467943499e-22  3.7345209871079e-22  0.0000000000000e+00
```

SCC-CUDA-C-K-CACHING

```
bin/dwarf-cloudsc-cuda-k-caching 1 262144 128
     NUMOMP=1, NGPTOT=262144, NPROMA=128, NGPBLKS=2048
     NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s
          1    262144    262144         0       128    0 :         45    714570 @ core#
          1    262144    262144      2048       128   -1 :       2360     13860 TOTAL
             Variable Dim             MinValue             MaxValue            AbsMaxErr         AvgAbsErr/GP          MaxRelErr-%
                PLUDE 2D1  0.0000000000000e+00  1.0267201089823e-04  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
             PCOVPTOT 2D3  0.0000000000000e+00  1.0000000000000e+00  3.6637359812630e-15  1.0209399286330e-15  3.8311567725177e-15      
     PRAINFRAC_TOPRFZ 2D1  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00  0.0000000000000e+00      
          [...]

2023-02-24 09:25 UTC, mlange05 requested changes
Ok, first of all, that is a fantastic amount of work and the resulting performance is a new record and an overall fantastic achievement. 

In principle this is done, I've only flagged a few  small Cmake issues and the misplaced initial timer in the driver that misses some of the initial data transfers. An entry into the README  would also be useful. Once these are fixed, this is all GTG from my side.

2023-02-24 09:25 UTC, mlange05 commented on bundle.yml
> +        cmake : ENABLE_CLOUDSC_CUDA={{value}}
Should we maybe add this to the `--with-cuda` option to turn these on? Or at least add a small comment to the README describing them and how to enable them? I realise that they hard-require Serialbox, so might not want to have them always on under `--with-cuda`.

2023-02-24 10:02 UTC, MichaelSt98 commented on src/cloudsc_cuda/cloudsc/cloudsc_c_hoist.cu
> +  const int klev = 137;  // Number of levels
Haven't tested it, but I see no reason for `klev` not to be an argument. Do you want me to change it?

2023-02-24 10:04 UTC, MichaelSt98 commented on src/cloudsc_cuda/cloudsc/cloudsc_c_k_caching.cu
> +    // Fortran counting is beautiful!
I agree ... `// Fortran counting is beautiful, but C counting is even more beautiful!` ? 😉

2023-02-24 17:45 UTC, reuterbal requested changes
This is absolutely fantastic and I have confirmed the insane speed-up on A100. Really great work!

I have left a few comments, would be great to address them please.

In addition, please add a description of these new variants to the README. Also, to make tests pass, update the verify-targets and run-targets files.

2023-02-24 17:45 UTC, reuterbal commented on src/cloudsc_cuda/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-hoist-caching
This test doesn't work, I suspect because the command is wrong. Should be bin/dwarf-cloudsc-cuda-hoist

2023-02-24 17:45 UTC, reuterbal commented on src/cloudsc_cuda/CMakeLists.txt
> +    CONDITION Serialbox_FOUND
This should have an `AND HAVE_CUDA`

2023-02-24 17:45 UTC, reuterbal commented on src/cloudsc_cuda/CMakeLists.txt
> +    ecbuild_info( "Serialbox not found, disabling C prototype" )
I would remove the else block, or at least update the error message

2023-02-24 17:45 UTC, reuterbal commented on src/cloudsc_cuda/cloudsc/load_state.cu
> +/*
That shows my ignorance for CUDA C: Is it customary to have all host-side code also with the ending `.cu`? I would have expected the various `cloudsc_driver`, as well as `cloudsc_validate`, `load_state` should actually be `.c` or `.cpp` files?

2023-02-28 14:40 UTC, reuterbal approved these changes
Many thanks, just one more typo in test binary (sorry if I missed this earlier), otherwise good to go in!

2023-02-28 14:40 UTC, reuterbal commented on src/cloudsc_cuda/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-hoist
Should be dwarf-cloudsc-cuda-hoist

2023-02-28 15:11 UTC, mlange05 approved these changes
Agreed! Many thanks for fixing all the last niggles. And congratulations again on a fantastic piece of work! And the new GPU performance record is well deserved! :grin: :shipit: :rocket: :tada: :fireworks:

2023-02-28 17:06 UTC, merged