Pure Python variant with test setup
ecmwf-ifs/dwarf-p-cloudsc pull request #51
Opened 2023-05-02 13:55 UTC by mlange05

_Note: This is the first in a list of planned PRs to homogenise the various Python variants we're investigating, so it won't be complete in the full sense, but instead pave the way for further infrastructure work._

The key contribution of this PR is the setup of a completely standalone pure Python variant of CLOUDSC that uses vanilla numpy array notation and produces correct results against the reference file. The kernel was originally generated via Loki, and there is a hidden option to re-generate the kernel file on-the-fly. The key idea here is that this will pave the way for a "pure on-the-fly JIT" variant that could generate Python-wrapped fortran kernels (without CMake setup), to slot into the provided Python driver. 

The initial setup, code-named `cloudscf2py` hsa also been set up for automatic CI setup and intergates with the bundle/cmake setup we use for the other variants. Unlike `cloudscpyiface` this uses CMake's `add_custom_target` and a full dependency chain of custom commands to install the alternative driver and symlink it into the build.

Further homogenisation with the PyIface variant is planned, but left for a follow-on PR.

The PR also puts the new driver/package into the same pip install as the `cloudsc4py` variant (and switches to `pyproject.toml` pip setup), but the GT4Py-based variant is not exposed to the CI runner, as it will likely be temporarily removed soon; again in a follow-on PR.  

This PR also removes the previously introduced pre-commit hooks, as they have become a little tedious on the Fortran development side.

2023-05-04 20:58 UTC, reuterbal requested changes
This looks great and the CMake integration is pretty neat!

I've flagged two or three small issues which would be good to resolve. And I've left a few questions/remarks that touch more on my understanding what the strategy is here. Let me know what your thoughts are there.

2023-05-04 20:58 UTC, reuterbal commented on src/cloudsc_python/drivers/cloudsc_f2py.py
> +    cloudsc_args = {
This looks a little odd - should there be default values in `cloudsc_args` or could this be merged with the statement below?

2023-05-04 20:58 UTC, reuterbal commented on src/cloudsc_python/drivers/cloudsc_f2py.py
> +def run_cloudsc_kernel(nthreads, ngptot, nproma, input_path, reference_path):
Am I missing something here or is this missing the input field expansion? Which means, any value for `ngptot` > 100 will not work?
Also, `nthreads` is not used (yet?).

2023-05-09 09:49 UTC, mlange05 commented on .github/workflows/build.yml
> +    name: Test on ${{ matrix.arch }} ${{ matrix.io_library_flag }} ${{ matrix.mpi_flag }} ${{ matrix.prec_flag }} ${{ matrix.gpu_flag }} ${{ matrix.loki_flag }} ${{ matrix.claw_flag }} ${{ matrix.pyi
Yes, was planning to homogenise all the python variants under a single flag, but that will come later. And you're right, for now we should make it explicit.

2023-05-09 09:57 UTC, mlange05 commented on src/cloudsc_python/src/cloudscf2py/cloudsc.F90
No, there are actually subtle restrictions for Python code that do not apply to the other variants - mainly due to the fact that we cannot access support modules and need to pass everything through the argument list at all times. I agree about the degree of duplication, but it's often warranted and meant to show the restrictions for individual cases.

2023-05-10 15:26 UTC, reuterbal reviewed
Thanks for addressing the comments! I think you have accidentally disabled the testing of this variant now because `python_flag` has not actually been renamed in the build matrix but only in some of the reporting (which is simply expanded to an empty string).

2023-05-11 07:31 UTC, merged