Enable gvmode and add nvidia/22.11 arch files
ecmwf-ifs/dwarf-p-cloudsc pull request #55
Opened 2023-06-12 16:08 UTC by reuterbal

This adds the gvmode (gang-vector-mode) flag for NVHPC on HPC2020, and adds updated arch files for nvidia/22.11

2023-06-21 09:55 UTC, mlange05 requested changes
Ok, in principle this looks great, but the `--with-cuda` mode breaks for me with the new env. I get:
```
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: cannot find -lcublasLt
/usr/bin/ld: cannot find -lcurand
```
in several places, which needs fixing before we can land this. I've verified the effect of `gvmode` though, and everything else looks super-neat and fast!

2023-07-10 16:12 UTC, reuterbal commented
Thanks for noticing this. Upon investigation, I could reproduce the issue and suspect a change in behaviour with respect to the `-cuda`/`-Mcuda` flag in NVHPC, possibly combined with specific target architecture specifications or CMake changes (which may have added this in the past automatically).

The specific issue, as far as I can tell, was that `cloudsc-common-lib` contains files with that option at compile time, for which nvfortran requires the option to be present at link time as well. However, the CMakeLists.txt specified this only for the build interface and was linked itself without it. Please verify if the latest commit resolves the issue for you.

2023-07-13 05:37 UTC, mlange05 commented
Great, yes, all good now! Thanks for fixing this, GTG. :shipit:

2023-07-13 05:37 UTC, mlange05 approved these changes

2023-07-13 05:38 UTC, merged