Update to new open-source FIELD_API
ecmwf-ifs/dwarf-p-cloudsc pull request #70
Opened 2024-02-05 09:28 UTC by awnawab

This PR updates the scc-field variant to use the new open-source FIELD_API. Notable changes are the use of the `FieldGang` feature to offload packed fields as a single contiguous entity, and the use of raw device pointers rather than host-mapped device pointers.

2024-02-05 10:06 UTC, reuterbal requested changes
Thanks, this looks great and very much looking forward to switching to the open-source field-api repository! Currently, the NVHPC tests fail to compile field-api and it would be good to get this sorted.

2024-02-05 10:06 UTC, reuterbal commented on bundle.yml
> +            ENABLE_SINGLE_PRECISION=OFF
Since this is effectively a global option in this form, we might want to simply put this at the top of the bundle.yml.

2024-02-05 15:57 UTC, awnawab commented
Converting this to a draft since I will need a FIELD_API build-system update to get around building with `acc=host` and `cuda` (for the CLOUSC CI).

2024-02-05 17:43 UTC, awnawab commented
Thanks again @reuterbal for all the help with this. The CI now builds the nvhpc runs with the `-acc=gpu` flag i.e. how we intend to build them for use. Because this inserts cuInit calls, we can't run these on the CI yet. Therefore, a separate nvhpc run is added with OpenACC explicitly disabled to test the loki and gpu variants (similar to the GNU CI runs).

2024-02-07 12:33 UTC, reuterbal commented
As discussed: Merging now and let's have a 1-line change PR once the new FIELD_API version has been tagged!

2024-02-07 12:33 UTC, merged