Nab atlas gpu field
ecmwf-ifs/dwarf-p-cloudsc pull request #89
Opened 2024-05-29 16:35 UTC by sbrdar

* add support for packing of nD-array variables into an (n+1)D-array using atlas::MultiField
* add src/cloudsc_gpu_atlas test for using Atlas GPU offloading with CUDA backend: has to be configured as "--with-atlas --with-gpu --with-cuda" using the bundle.yml
* Atlas support 'pageable', 'pinned', and 'pinned + mapped' memory settings on the host and the device for offloading
* temporarily switch to Atlas' branch 'feature/gpu_discontiguous_data'

2025-04-29 06:55 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/dwarf_cloudsc_atlas.F90
> +  ! IF (NITER == 1) CALL GLOBAL_ATLAS_STATE%VALIDATE(FSET, FSPACE, NGPTOTG)
This should not be disabled

2025-04-29 12:24 UTC, wdeconinck requested changes
Thanks @sbrdar for showing the power of atlas and pluto.
I have some suggestions.

2025-04-29 12:24 UTC, wdeconinck commented on arch/eurohpc/lumi/cray-gpu/17.0.1/env.sh
> +) Copyright 1988- ECMWF.
Revert this change

2025-04-29 12:24 UTC, wdeconinck commented on arch/eurohpc/lumi/cray-gpu/17.0.1/env.sh
> +  fi
This change is not needed.

2025-04-29 12:24 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    REAL(KIND=JPRB), CONTIGUOUS  :: PLCRIT_AER(:,:,:)
I suggest to add INTENT for this and following arguments

2025-04-29 12:24 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    NGPBLKS = (NGPTOT / NPROMA) + MIN(MOD(NGPTOT,NPROMA), 1)
```suggestion
    NGPBLKS = FIELD%SHAPE(4)
```

2025-04-29 12:24 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +  SUBROUTINE CLOUDSC_DRIVER(FSET, NUMOMP, NGPTOTG, KFLDX, PTSPHY)
NGPTOTG, KFLDX are unused variables (except perhaps for a print) and can be refactored out.

Also not sure NUMOMP makes sense in the GPU context. Perhaps this should be forcefully set to 1, @reuterbal ?

2025-04-29 12:24 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +        PRINT *, "HOIST_POOL must be -1, 0, or 1. Exiting."
I'd remove the '-1' option for HOIST_POOL, and don't do the `acc enter data create`, and only use pluto.

2025-04-29 12:24 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +        & ZPFPLSX(:,:,:,:), ZLNEG(:,:,:,:), ZQXN2D(:,:,:,:)
This can be factored out as a CLOUD_SCC_HOIST_DATA type, (including the TYPE(pluto_allocator))
Then the lines below to allocate and deallocate could be member functions of this type.

2025-04-29 14:42 UTC, wdeconinck commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      PRINT *, "ERROR: MultiField not avaiable in Atlas/develop"
Correction, it is now :)

2025-04-29 14:46 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/dwarf_cloudsc_atlas.F90
> +USE ATLAS_MULTIFIELD_MODULE
```suggestion
```
can be removed.

2025-04-29 15:06 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +            cloudsc-common-${prec}-atlas
```suggestion
            cloudsc-common-atlas-${prec}
```
I'd assume that ${prec} should go at the end of the name. Of course also change everywhere used and defined.

2025-05-08 12:14 UTC, sbrdar commented on src/cloudsc_gpu_atlas/dwarf_cloudsc_atlas.F90
> +  ! IF (NITER == 1) CALL GLOBAL_ATLAS_STATE%VALIDATE(FSET, FSPACE, NGPTOTG)
Enabled again to execute every time after the first iteration.

2025-05-08 12:14 UTC, sbrdar commented on arch/eurohpc/lumi/cray-gpu/17.0.1/env.sh
> +) Copyright 1988- ECMWF.
Done. Thanks!

2025-05-08 12:14 UTC, sbrdar commented on arch/eurohpc/lumi/cray-gpu/17.0.1/env.sh
> +  fi
Thanks! It has been removed.

2025-05-08 12:15 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    REAL(KIND=JPRB), CONTIGUOUS  :: PLCRIT_AER(:,:,:)
Thanks. I have added the INTENTs.

2025-05-08 12:15 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    NGPBLKS = (NGPTOT / NPROMA) + MIN(MOD(NGPTOT,NPROMA), 1)
Good point to avoid inconsistencies. Thanks!

2025-05-08 12:15 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +  SUBROUTINE CLOUDSC_DRIVER(FSET, NUMOMP, NGPTOTG, KFLDX, PTSPHY)
I have removed both unused arguments in the CLOUDSC_DRIVER subroutine.

2025-05-08 12:15 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +        PRINT *, "HOIST_POOL must be -1, 0, or 1. Exiting."
I have removed the '-1' option, we rely on 'pluto' to allocate the hoisting variables.

2025-05-08 12:17 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +        & ZPFPLSX(:,:,:,:), ZLNEG(:,:,:,:), ZQXN2D(:,:,:,:)
This approach is nice but it drifts away from the rest of the code with i.e. FIELD_API. Perhaps we can think of it together with @reuterbal?

2025-05-08 12:17 UTC, sbrdar commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      PRINT *, "ERROR: MultiField not avaiable in Atlas/develop"
Removed and also replaced the old usage of MultiField creation in the CPU version with the new one, similar to how it is done for the GPU version.

2025-05-08 12:18 UTC, sbrdar commented on src/cloudsc_gpu_atlas/dwarf_cloudsc_atlas.F90
> +USE ATLAS_MULTIFIELD_MODULE
Thanks. It has been removed now.

2025-05-08 12:18 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +            cloudsc-common-${prec}-atlas
This is the design of @reuterbal to have libraries, like atlas etc, attached to cloudsc-common after the precision. If @reuterbal agrees to change it in his build system, I have no problem changing it in the above CMake file.

2025-05-08 12:19 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +        & ZPFPLSX(:,:,:,:), ZLNEG(:,:,:,:), ZQXN2D(:,:,:,:)
Sure you could leave it.

2025-05-08 12:41 UTC, wdeconinck commented
I would advise to reuse CPU and GPU codes where possible, to avoid code duplication and maintainability.
In particular, I think the validate, and creation of the fields and loading the data is probably identical.
The CPU OpenMP driver or GPU OpenACC driver can then be called independently.

2025-05-08 16:43 UTC, sbrdar commented
> I would advise to reuse CPU and GPU codes where possible, to avoid code duplication and maintainability. In particular, I think the validate, and creation of the fields and loading the data is probably identical. The CPU OpenMP driver or GPU OpenACC driver can then be called independently.

I have now reused the expand_atlas_mod and validate_atlas_mod from 'cloudsc_fortran_atlas' in 'cloudsc_gpu_atlas'.

2025-05-26 04:41 UTC, reuterbal requested changes
Many thanks for this, this is an exciting step forward and I'm very much looking forward to bringing this in! Apologies for the long review time, I did want to do this properly and really test this with the appropriate care.

First of all, the SCC and SCC-K-CACHING variants work flawlessly in single and double precision and also on larger problem sizes and produce very nice performance results! Well done!

- [ ] I left some remarks in-line, please address them. Most of the comments relate to the CMake integration, which needs some improvements. Also, I would like to make sure the tests work correctly and ideally switch Atlas on for them in a subsequent PR both in hpc-ci and at least on GH Actions configuration.

- [ ] For some reason, the per-thread throughput reporting (which should measure the kernel execution time) seems to not work correctly, e.g., on gh1 it simply shows 0:

```
$ bin/dwarf-cloudsc-gpu-scc-k-caching-atlas-dp 1 163840 128
Warning! Processor does not support trapping of floating-point exceptions.
 LMULTIFIELD =   F
 NGPTOTG     =        163840
 NGPTOT      =        163840
 NBLKS       =          1280
 NPROMA      =           128
 Host allocate [ms]:             9
 LMULTIFIELD =   F
 NGPTOTG     =        163840
 NGPTOT      =        163840
 NBLKS       =          1280
 NPROMA      =           128
 Host allocate [ms]:             1

### ITERATION 1/1
     NUMPROC=1, NUMOMP=1, NGTOT=163840, NGPTOTG=163840, NPROMA=128, NGPBLKS=1280
 Device allocate [ms]:            32
 Reference MFLOP count for 100 columns :  12.48232900
     NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s     col/s
          1    163840         0         0       128    0 :         21         0   7784519 @ rank#0:core#62
          1    163840         0      1280       128   -1 :         74    275665   2208443 : TOTAL @ rank#0
    1 x   1    163840         0      1280       128   -1 :         74    275665   2208443 : TOTAL
```

- [ ] Finally, after fixing the issues mentioned in the comments, the following test doesn't work for me right now on AC GPUs (both in single and double precision and with and without OpenMP):

```
21/46 Test: dwarf-cloudsc-fortran-atlas-dp-serial
Command: "/.../nab_atlas_gpu_field/build/bin/dwarf-cloudsc-fortran-atlas-dp" "1" "100" "16"
Directory: /.../nab_atlas_gpu_field/build
"dwarf-cloudsc-fortran-atlas-dp-serial" start time: May 26 06:09 CEST
Output:
----------------------------------------------------------
  LMULTIFIELD:   T
(E) Exception: FieldSet: cannot find field "PLCRIT_AER"  (/.../nab_atlas_gpu_field/source/atlas/src/atlas/field/FieldSet.cc:120 field)

(E) =========================================
(E) TERMINATING dwarf-cloudsc-fortran-atlas-dp
(E) -----------------------------------------
(E) FieldSet: cannot find field "PLCRIT_AER"
(E) -----------------------------------------
(E) LOCATION:  (/.../nab_atlas_gpu_field/source/atlas/src/atlas/field/FieldSet.cc:120 field)
(E) -----------------------------------------
(E) BACKTRACE
(E) ------------------
```

And the SCC-HOIST test fails with a segfault:
```
24/46 Test: dwarf-cloudsc-gpu-scc-hoist-atlas-dp
Command: "/.../nab_atlas_gpu_field/build/bin/dwarf-cloudsc-gpu-scc-hoist-atlas-dp" "1" "1000" "128"
Directory: /.../nab_atlas_gpu_field/build/cloudsc-dwarf/src/cloudsc_gpu_atlas.dp/../../..
"dwarf-cloudsc-gpu-scc-hoist-atlas-dp" start time: May 26 06:09 CEST
Output:
----------------------------------------------------------
 LMULTIFIELD =   F
 NGPTOTG     =          1000
 NGPTOT      =          1000
 NBLKS       =             8
 NPROMA      =           128
 LMULTIFIELD =   F
 NGPTOTG     =          1000
 NGPTOT      =          1000
 NBLKS       =             8
 NPROMA      =           128

### ITERATION 1/1
     NUMPROC=1, NUMOMP=1, NGTOT=1000, NGPTOTG=1000, NPROMA=128, NGPBLKS=8
<end of output>
Test time =   0.38 sec
----------------------------------------------------------
Test Failed.
```

2025-05-26 04:41 UTC, reuterbal commented on arch/toolchains/ecmwf-hpc2020-nvhpc.cmake
> +set( OpenACC_C_FLAGS "${OpenACC_Fortran_FLAGS}")
should this not be a CACHE variable, too?

2025-05-26 04:41 UTC, reuterbal commented on bundle.yml
> +            ATLAS_ENABLE_CUDA={{value}}
Is CUDA required, or does it work also with only OpenACC? Since the CUDA support can be enabled separately via `--with-cuda`, it would make more sense to restrict this to ATLAS_ENABLE_ACC here if possible.

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +)
We have retired the per-variant ecbuild options because it did get a little out of hand, making it hard to spot what options or packages were selected or not found. Instead, we build all viable variants that are possible with the found dependencies. Since the include in `src/CMakeLists.txt` already ensures that Atlas is available, we can skip the ecbuild_add_option here and the `if (HAVE_CLOUDSC_GPU_SCC_ATLAS)`, `if(HAVE_CLOUDSC_GPU_SCC_HOIST_ATLAS)` etc. below.

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +            ../cloudsc_fortran_atlas/validate_atlas_mod.F90
I think we should maybe move these into the common lib at some point? 

In any case, since they are built for every target here, you get problems with aliasing in the .mod files and potential race conditions in parallel builds. Please try a build with Ninja, which is great at catching these issues:
```
ninja: build stopped: multiple rules generate cloudsc-dwarf/src/cloudsc_gpu_atlas.dp/cloudsc_global_atlas_state_mod.mod.
```

Therefore, as a minimum you will need to set per-target module directories here. See for example the relevant snippet from the GPU variants:

https://github.com/ecmwf-ifs/dwarf-p-cloudsc/blob/b42aacae409f3a7bec13bdf0f4c75bee5f5989ba/src/cloudsc_gpu/CMakeLists.txt#L35-L38

2025-05-26 04:41 UTC, reuterbal commented on src/CMakeLists.txt
> +    if( HAVE_CUDA OR HAVE_HIP )
I'm wondering, are CUDA/HIP really required to build these variants? It's not performant but a CPU build should work and be runnable, no?

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +            cloudsc-common-${prec}-atlas
Either is fine with me - I wasn't particularly strict about the naming scheme there, only trying to avoid any clashes and limiting the programming model exposure in the common libs.

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +endif()
This is redundant, please remove. Test data is being handled centrally in CMake now.

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +#endif()
Can be deleted?

2025-05-26 04:41 UTC, reuterbal commented on arch/ecmwf/hpc2020/nvhpc/22.11/env.sh
> +module_load cmake/3.25.2
CMake 3.28 is loaded further down
```suggestion
module_load cmake/3.25.2
```

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/../../..
This is where the central input file mechanics will place the test inputs. Please change this also for the other test definitions in this file.
```suggestion
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
```

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-hoist-atlas
```suggestion
        TARGET dwarf-cloudsc-gpu-scc-hoist-atlas-${prec}
        COMMAND bin/dwarf-cloudsc-gpu-scc-hoist-atlas-${prec}
```

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-k-caching-atlas
```suggestion
        TARGET dwarf-cloudsc-gpu-scc-k-caching-atlas-${prec}
        COMMAND bin/dwarf-cloudsc-gpu-scc-k-caching-atlas-${prec}
```

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-atlas
Tests don't pass because target name doesn't match:
```suggestion
        TARGET dwarf-cloudsc-gpu-scc-atlas-${prec}
        COMMAND bin/dwarf-cloudsc-gpu-scc-atlas-${prec}
```

2025-05-26 04:41 UTC, reuterbal commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    CALL GET_ENVIRONMENT_VARIABLE("HOIST_POOL", VALUE=HOIST_POOL_STR, LENGTH=HOIST_POOL_STR_LEN)
Can you document this enviornment variable in the readme please?

2025-05-26 04:41 UTC, reuterbal commented on arch/ecmwf/gh/env.sh
The env doesn't fully work on the Grace Hopper node, the prototype1 variant and the CUDA variants throw various compiler errors for me. Have you seen the same?

I'm ok with integrating it nonetheless since it been used to test the Atlas variant, but maybe add a print to the env.sh file that clearly states that the CUDA C and prototype1 variants are known to not work with this.

2025-06-10 23:44 UTC, sbrdar commented on arch/toolchains/ecmwf-hpc2020-nvhpc.cmake
> +set( OpenACC_C_FLAGS "${OpenACC_Fortran_FLAGS}")
You are right, I did not find OpenACC_C_FLAGS in the cache list and it should be there. I am adding CACHE here.

2025-06-10 23:44 UTC, sbrdar commented on bundle.yml
> +            ATLAS_ENABLE_CUDA={{value}}
Good point. CUDA is not required on --with-acc, Atlas can resolve now itself what it needs in the background.

2025-06-10 23:44 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +)
Indeed, cmake was more involved with condition testing. I am happy to clean up all add_option-s now, assuming the conditions are satisfied.

2025-06-10 23:44 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +            ../cloudsc_fortran_atlas/validate_atlas_mod.F90
A valuable comment, much appreciated. I have at the moment opted for the minimum after your suggestion, which seems to work.

2025-06-10 23:44 UTC, sbrdar commented on src/CMakeLists.txt
> +    if( HAVE_CUDA OR HAVE_HIP )
It is true. We can compile and run Atlas GPU code for CPU. I have removed the CUDA/HIP requirement here, albeit without thoroughly testing.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +endif()
Thanks. Cleaned up now.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +#endif()
Thanks. Removed now.

2025-06-10 23:45 UTC, sbrdar commented on arch/ecmwf/hpc2020/nvhpc/22.11/env.sh
> +module_load cmake/3.25.2
Indeed. I have removed 3.25.2 from the list.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/../../..
Done. Thanks.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-hoist-atlas
Cleaned up now. Thanks!

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-k-caching-atlas
... and this one as well.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +        COMMAND bin/dwarf-cloudsc-gpu-scc-atlas
... and this one as well.

2025-06-10 23:45 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +    CALL GET_ENVIRONMENT_VARIABLE("HOIST_POOL", VALUE=HOIST_POOL_STR, LENGTH=HOIST_POOL_STR_LEN)
Thanks. Done. Also, added information on dwarf-cloudsc-gpu-scc-k-caching-atlas.

2025-06-15 18:11 UTC, reuterbal requested changes
Many thanks for addressing all the comments @sbrdar! This looks very good now.

I just left two small requests inline to add test variants for the options introduced via environment variables to make sure these features are tested appropriately.

One thing I noticed, however, is that when not specifying the `--with-cuda=ON` option, the atlas-scc and atlas-scc-hoist variants seem to segfault. But tests work fine with the `--with-cuda=ON` option. Tested with nvidia/24.5 on AC:

```sh
srun -c 64 ./cloudsc-bundle build --arch arch/ecmwf/hpc2020/nvhpc/24.5/ --with-atlas=ON --build-dir build.nvidia [--with-cuda=ON]
cd build.nvidia
source env.sh
srun -q dg -t 0:30:00 -n 1 -c 32 --mem=120G --gpus=1 ctest
```

Can you please have another look what might be the issue here?

2025-06-15 18:11 UTC, reuterbal commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +)
Sorry for not spotting this earlier. Can we add a second test that enables the hoist pool?
```suggestion
ecbuild_add_test(
    TARGET dwarf-cloudsc-gpu-scc-hoist-atlas-${prec}
    COMMAND bin/dwarf-cloudsc-gpu-scc-hoist-atlas-${prec}
    ARGS 1 1000 128
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    OMP 1
)
ecbuild_add_test(
    TARGET dwarf-cloudsc-gpu-scc-hoist-pool-atlas-${prec}
    COMMAND bin/dwarf-cloudsc-gpu-scc-hoist-atlas-${prec}
    ARGS 1 1000 128
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    OMP 1
    ENVIRONMENT HOIST_POOL=1
)
```

2025-06-15 18:11 UTC, reuterbal commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +    CALL GET_ENVIRONMENT_VARIABLE("CLOUDSC_ATLAS_MULTIFIELD", CENV, CENV_LEN)
Would you mind also adding a second test with `CLOUDSC_ATLAS_MULTIFIELD=1`?

2025-06-18 13:12 UTC, sbrdar commented
> Many thanks for addressing all the comments @sbrdar! This looks very good now.
> 
> I just left two small requests inline to add test variants for the options introduced via environment variables to make sure these features are tested appropriately.
> 
> One thing I noticed, however, is that when not specifying the `--with-cuda=ON` option, the atlas-scc and atlas-scc-hoist variants seem to segfault. But tests work fine with the `--with-cuda=ON` option. Tested with nvidia/24.5 on AC:
> 
> ```shell
> srun -c 64 ./cloudsc-bundle build --arch arch/ecmwf/hpc2020/nvhpc/24.5/ --with-atlas=ON --build-dir build.nvidia [--with-cuda=ON]
> cd build.nvidia
> source env.sh
> srun -q dg -t 0:30:00 -n 1 -c 32 --mem=120G --gpus=1 ctest
> ```
> 
> Can you please have another look what might be the issue here?

We have not considered this so far, but it has been fixed now. A partial FE_INVALID check on the CLOUDSC function had to be omitted in the release build when running on CPU. Also, dwarf files using Atlas data should not use OpenACC if Atlas does not have CUDA/HIP enabled. OpenACC accesses Atlas data structured through the 'device_ptr' pragma call.

2025-06-18 13:13 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +)
Thanks for the hint. It has been added.

2025-06-18 13:13 UTC, sbrdar commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +    CALL GET_ENVIRONMENT_VARIABLE("CLOUDSC_ATLAS_MULTIFIELD", CENV, CENV_LEN)
... and this as well. Thank you!

2025-06-18 13:45 UTC, wdeconinck requested changes

2025-06-18 13:45 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +!#endif
```suggestion
    LOGICAL :: LL_HALT_INVALID
    CALL IEEE_GET_HALTING_MODE(IEEE_INVALID, LL_HALT_INVALID)
    CALL IEEE_SET_HALTING_MODE(IEEE_INVALID, .FALSE.)
```
Also please write a little comment stating that this temporarily disables floating-point-trapping of FE_INVALID caused by too aggressive optimisation within the CLOUDSC function.

2025-06-18 13:45 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +!#endif
```suggestion
    IF (LL_HALT_INVALID) CALL IEEE_SET_HALTING_MODE(IEEE_INVALID,  .TRUE.)
```
Only set it back to `.TRUE.` if it was `.TRUE.` before (`LL_HALT_INVALID`)

2025-06-18 13:45 UTC, wdeconinck commented on bundle.yml
> +            ATLAS_ENABLE_ACC=OFF
CUDA, HIP, ACC are OFF by default, so no need to add here.

2025-06-18 13:45 UTC, wdeconinck commented on src/common/CMakeLists.txt
> +    endif()
Write a comment that Atlas was not compiled with GPU support, so that OpenACC instructions should be ignored in the dwarf

2025-06-18 14:06 UTC, sbrdar commented on src/common/CMakeLists.txt
> +    endif()
Good point. I have added a cmake warning on disabling OpenACC instruction when GPU support has been disabled in Atlas.

2025-06-18 14:06 UTC, sbrdar commented on bundle.yml
> +            ATLAS_ENABLE_ACC=OFF
Indeed, they are off in Atlas. Hence, removed here. Thanks!

2025-06-18 14:06 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +!#endif
Fixed. Thanks!

2025-06-18 14:06 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +!#endif
Many thanks. It has been added.

2025-06-18 14:43 UTC, sbrdar commented
> Many thanks for this, this is an exciting step forward and I'm very much looking forward to bringing this in! Apologies for the long review time, I did want to do this properly and really test this with the appropriate care.
> 
> First of all, the SCC and SCC-K-CACHING variants work flawlessly in single and double precision and also on larger problem sizes and produce very nice performance results! Well done!
> 
> * [ ]  I left some remarks in-line, please address them. Most of the comments relate to the CMake integration, which needs some improvements. Also, I would like to make sure the tests work correctly and ideally switch Atlas on for them in a subsequent PR both in hpc-ci and at least on GH Actions configuration.
> * [ ]  For some reason, the per-thread throughput reporting (which should measure the kernel execution time) seems to not work correctly, e.g., on gh1 it simply shows 0:
> 
> ```
> $ bin/dwarf-cloudsc-gpu-scc-k-caching-atlas-dp 1 163840 128
> Warning! Processor does not support trapping of floating-point exceptions.
>  LMULTIFIELD =   F
>  NGPTOTG     =        163840
>  NGPTOT      =        163840
>  NBLKS       =          1280
>  NPROMA      =           128
>  Host allocate [ms]:             9
>  LMULTIFIELD =   F
>  NGPTOTG     =        163840
>  NGPTOT      =        163840
>  NBLKS       =          1280
>  NPROMA      =           128
>  Host allocate [ms]:             1
> 
> ### ITERATION 1/1
>      NUMPROC=1, NUMOMP=1, NGTOT=163840, NGPTOTG=163840, NPROMA=128, NGPBLKS=1280
>  Device allocate [ms]:            32
>  Reference MFLOP count for 100 columns :  12.48232900
>      NUMOMP    NGPTOT  #GP-cols     #BLKS    NPROMA tid# : Time(msec)  MFlops/s     col/s
>           1    163840         0         0       128    0 :         21         0   7784519 @ rank#0:core#62
>           1    163840         0      1280       128   -1 :         74    275665   2208443 : TOTAL @ rank#0
>     1 x   1    163840         0      1280       128   -1 :         74    275665   2208443 : TOTAL
> ```
> 
>  * [x]  Finally, after fixing the issues mentioned in the comments, the following test doesn't work for me right now on AC GPUs (both in single and double precision and with and without OpenMP):
> 
> ```
> 21/46 Test: dwarf-cloudsc-fortran-atlas-dp-serial
> Command: "/.../nab_atlas_gpu_field/build/bin/dwarf-cloudsc-fortran-atlas-dp" "1" "100" "16"
> Directory: /.../nab_atlas_gpu_field/build
> "dwarf-cloudsc-fortran-atlas-dp-serial" start time: May 26 06:09 CEST
> Output:
> ----------------------------------------------------------
>   LMULTIFIELD:   T
> (E) Exception: FieldSet: cannot find field "PLCRIT_AER"  (/.../nab_atlas_gpu_field/source/atlas/src/atlas/field/FieldSet.cc:120 field)
> 
> (E) =========================================
> (E) TERMINATING dwarf-cloudsc-fortran-atlas-dp
> (E) -----------------------------------------
> (E) FieldSet: cannot find field "PLCRIT_AER"
> (E) -----------------------------------------
> (E) LOCATION:  (/.../nab_atlas_gpu_field/source/atlas/src/atlas/field/FieldSet.cc:120 field)
> (E) -----------------------------------------
> (E) BACKTRACE
> (E) ------------------
> ```
> 
> And the SCC-HOIST test fails with a segfault:
> 
> ```
> 24/46 Test: dwarf-cloudsc-gpu-scc-hoist-atlas-dp
> Command: "/.../nab_atlas_gpu_field/build/bin/dwarf-cloudsc-gpu-scc-hoist-atlas-dp" "1" "1000" "128"
> Directory: /.../nab_atlas_gpu_field/build/cloudsc-dwarf/src/cloudsc_gpu_atlas.dp/../../..
> "dwarf-cloudsc-gpu-scc-hoist-atlas-dp" start time: May 26 06:09 CEST
> Output:
> ----------------------------------------------------------
>  LMULTIFIELD =   F
>  NGPTOTG     =          1000
>  NGPTOT      =          1000
>  NBLKS       =             8
>  NPROMA      =           128
>  LMULTIFIELD =   F
>  NGPTOTG     =          1000
>  NGPTOT      =          1000
>  NBLKS       =             8
>  NPROMA      =           128
> 
> ### ITERATION 1/1
>      NUMPROC=1, NUMOMP=1, NGTOT=1000, NGPTOTG=1000, NPROMA=128, NGPBLKS=8
> <end of output>
> Test time =   0.38 sec
> ----------------------------------------------------------
> Test Failed.
> ```

Thank you very much @reuterbal for having a thorough look on Atlas part of the dwarf! Much appreciated!

In addition to my previous answers, I can add here:
1) the per-thread throughput reporting is back again;
2) the CPU code version in the folder 'cloudsc-fortran-atlas' has been fixed;
3) the GPU code version in the folder 'clodusc-gpu-atlas' has been fixed to also run on CPU;
4) if cmake omits the folder 'prototype1' and one or two more, you can compile the Atlas part of the dwarf on GraceHopper as well. I have checked that the code executes on GH200 correctly.

So far, re Atlas seems to work in intended configurations, but I might have missed a configuration of two which we do not support through our tests. I will be happy to look into a specific problems should such needed to be fixed.

Again, many thanks for your invaluable comments!

2025-06-18 14:46 UTC, sbrdar commented
> > I would advise to reuse CPU and GPU codes where possible, to avoid code duplication and maintainability. In particular, I think the validate, and creation of the fields and loading the data is probably identical. The CPU OpenMP driver or GPU OpenACC driver can then be called independently.
> 
> I have now reused the expand_atlas_mod and validate_atlas_mod from 'cloudsc_fortran_atlas' in 'cloudsc_gpu_atlas'.

Many thanks for review this PR, @wdeconinck ! Very insightful hints and remarks! Thank you!

2025-06-19 22:45 UTC, wdeconinck requested changes

2025-06-19 22:45 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +#if (ATLAS_HAVE_GPU == 0)
I don't think the ATLAS_HAVE_GPU variable is defined at all. You should remove the #if, just keeping the IEEE_*_HALTING_MODE statements.

2025-06-19 22:45 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +#if (ATLAS_HAVE_GPU == 0)
Also this #if should go, but keep what's nested.

2025-06-24 12:26 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +#if (ATLAS_HAVE_GPU == 0)
Thanks. Removed now.

2025-06-24 12:26 UTC, sbrdar commented on src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90
> +#if (ATLAS_HAVE_GPU == 0)
.. and this one as well. Thanks.

2025-07-09 08:19 UTC, wdeconinck commented
linux-nvhpc ci fails with:
```
FAILED: [code=2] src/cloudsc_gpu_atlas.dp/CMakeFiles/dwarf-cloudsc-gpu-scc-atlas-dp.dir/cloudsc_driver_scc_mod.F90.o src/cloudsc_gpu_atlas.dp/module-dwarf-cloudsc-gpu-scc-atlas/cloudsc_driver_scc_mod.mod 
  /opt/nvhpc/Linux_x86_64/24.5/compilers/bin/nvfortran -I/home/runner/work/dwarf-p-cloudsc/dwarf-p-cloudsc/src/cloudsc_gpu_atlas -I/home/runner/work/dwarf-p-cloudsc/dwarf-p-cloudsc/src/common/include -I/home/runner/work/dwarf-p-cloudsc/dwarf-p-cloudsc/build/src/common.dp/module-atlas -I/home/runner/work/_temp/install/atlas/include -I/home/runner/work/_temp/install/atlas/module/atlas -I/home/runner/work/_temp/install/fckit/include -I/home/runner/work/_temp/install/fckit/module/fckit -I/home/runner/work/_temp/install/fckit/include/fckit -I/home/runner/work/_temp/deps/hdf5/include -Mlarge_arrays -g -O0 -Mbounds -traceback -module src/cloudsc_gpu_atlas.dp/module-dwarf-cloudsc-gpu-scc-atlas -fPIE -mp -c src/cloudsc_gpu_atlas.dp/CMakeFiles/dwarf-cloudsc-gpu-scc-atlas-dp.dir/cloudsc_driver_scc_mod.F90-pp.f90 -o src/cloudsc_gpu_atlas.dp/CMakeFiles/dwarf-cloudsc-gpu-scc-atlas-dp.dir/cloudsc_driver_scc_mod.F90.o
  NVFORTRAN-F-0004-Unable to open MODULE file pluto_module.mod (/home/runner/work/dwarf-p-cloudsc/dwarf-p-cloudsc/src/cloudsc_gpu_atlas/cloudsc_driver_scc_mod.F90: 30)
  NVFORTRAN/x86-64 Linux 24.5-1: compilation aborted
  ```
 Perhaps we need to link the target `dwarf-cloudsc-gpu-scc-atlas-${prec}` with `pluto_f` directly.

2025-07-09 08:25 UTC, wdeconinck commented
The runner OS for intel-classic should be an older ubuntu-22.04. intel-llvm with ubuntu-24.04 should be OK.

2025-07-09 08:27 UTC, wdeconinck commented
The ci for "linux gnu-14" is failing in atlas where OpenMP is seemingly detected by CMake with -fopenmp flag but then the C++ code cannot find the "omp.h" include file for some weird reason. To be investigated why...

2025-07-09 12:22 UTC, wdeconinck commented
> Perhaps we need to link the target `dwarf-cloudsc-gpu-scc-atlas-${prec}` with `pluto_f` directly.

This was already the case, so the problem is in the export of pluto in install-interface.
This is fixed in atlas branch hotfix/0.43.1, to be released as 0.43.1 once these tests pass.

Please update in builds.yml "refs/tags/0.43.0" to "hotfix/0.43.1" to see. If all works, I will release 0.43.1 and then we can update the tag once more to "refs/tags/0.43.1"

2025-07-09 14:23 UTC, wdeconinck commented
It seems the OpenMP for the gnu-14 on ubuntu-24.04 is really problematic. Perhaps we need to turn off OMP feature for this entire build?

intel-classic build shows that in case of multifield the expand is creating temporaries. This is because the dimensions of the second argument field have contiguous dimensions whereas the field passed is discontiguous slice. Changing the dimensions from `(nproma, nlev, nblk)` to `(:,:,:)` will solve this.

```
 43/48 Test #43: dwarf-cloudsc-gpu-scc-k-caching-multifield-atlas-sp ....***Failed    1.02 sec
   LMULTIFIELD =  T
   NGPTOTG     =         1000
   NGPTOT      =         1000
   NBLKS       =            8
   NPROMA      =          128
   Host allocate [ms]:       -56598
  forrtl: warning (406): fort: (1): In call to EXPAND_R2, an array temporary was created for argument #2
  
  Image              PC                Routine            Line        Source             
  dwarf-cloudsc-gpu  0000000000443103  expand_atlas_mod_          87  expand_atlas_mod.F90
  dwarf-cloudsc-gpu  000000000043847F  cloudsc_global_at         176  cloudsc_global_atlas_state_mod.F90
  dwarf-cloudsc-gpu  00000000004DA241  MAIN__                     78  dwarf_cloudsc_atlas.F90
  dwarf-cloudsc-gpu  000000000042B6CD  Unknown               Unknown  Unknown
  libc.so.6          00007FC53F229D90  Unknown               Unknown  Unknown
  libc.so.6          00007FC53F229E40  __libc_start_main     Unknown  Unknown
  dwarf-cloudsc-gpu  000000000042B5E5  Unknown               Unknown  Unknown
  ```

2025-07-09 14:55 UTC, wdeconinck commented on src/common/module/expand_mod.F90
> +    use omp_lib
@sbrdar no need to add "use omp_lib" unless you are calling actual routines instead of pragmas.

2025-07-10 08:57 UTC, wdeconinck commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      DO IVAR = 1, 24
I don't like the number 24 here. Can this be a more descriptive size variable?

2025-07-10 08:57 UTC, wdeconinck commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      DO IVAR = 1, 14
I don't like the number 14 here. Can this be a more descriptive size variable?

2025-07-10 08:57 UTC, wdeconinck commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +# (C) Copyright 1988- ECMWF.
1988 -> 2025

2025-07-10 08:57 UTC, wdeconinck commented on arch/ecmwf/gh/toolchain.cmake
> +# (C) Copyright 1988- ECMWF.
1988 -> 2025

2025-07-10 08:57 UTC, wdeconinck commented on arch/ecmwf/gh/env.sh
> +# (C) Copyright 1988- ECMWF.
1988 -> 2025

2025-07-10 09:53 UTC, sbrdar commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      DO IVAR = 1, 24
Good point. Thanks! We now use NUM_IN_MFIELDS and NUM_OUT_MFIELDS in cloudsc_fortran_atlas. Also, a similar change has been done in cloudsc_gpu_atlas.

2025-07-10 09:54 UTC, sbrdar commented on src/cloudsc_fortran_atlas/cloudsc_global_atlas_state_mod.F90
> +      DO IVAR = 1, 14
Done. See previous comment.

2025-07-10 09:54 UTC, sbrdar commented on src/cloudsc_gpu_atlas/CMakeLists.txt
> +# (C) Copyright 1988- ECMWF.
Done.

2025-07-10 09:54 UTC, sbrdar commented on arch/ecmwf/gh/toolchain.cmake
> +# (C) Copyright 1988- ECMWF.
Done.

2025-07-10 09:56 UTC, sbrdar commented on arch/ecmwf/gh/env.sh
> +# (C) Copyright 1988- ECMWF.
Done. Thanks!

2025-07-10 15:56 UTC, wdeconinck commented
All CI is green now! I guess now it's time to clean up (rebase etc) the branch a bit before merging it.
Perhaps @reuterbal can have another review round to double check and approve.

2025-07-10 16:02 UTC, wdeconinck commented on .github/workflows/build-hpc.yml
> +              #SBATCH --cpus-per-task=64
This makes for speedy compilation, giving access to 256 threads on the hpc node.

2025-07-10 16:03 UTC, wdeconinck commented on .github/workflows/build-hpc.yml
> +              #SBATCH --cpus-per-task=7
This gives access to 56 threads to compile on the dev-g LUMI node.
Empirically I found 56 is the maximum one can get.

2025-07-10 16:05 UTC, wdeconinck commented on .github/workflows/build-hpc.yml
> +    - 'nab_atlas_gpu_field'
This should be removed before merging!

2025-07-10 16:06 UTC, wdeconinck commented on arch/ecmwf/gh/env.sh
> +export PATH=/perm/nawd/software/gh/cmake/3.30.3/bin:$PATH
This needs a more permanent solution!

2025-07-11 09:28 UTC, reuterbal approved these changes
Many thanks, to me this looks very good! The TLC applied to the build-hpc workflow is also much appreciated

2025-07-11 09:28 UTC, reuterbal commented on .github/workflows/build-hpc.yml
> +              #SBATCH --cpus-per-task=7
Yes, that's correct - see the disclaimer here: https://docs.lumi-supercomputer.eu/runjobs/scheduled-jobs/lumig-job/

2025-07-11 09:46 UTC, sbrdar commented on .github/workflows/build-hpc.yml
> +    - 'nab_atlas_gpu_field'
Done.

2025-07-14 13:06 UTC, wdeconinck approved these changes

2025-07-14 13:07 UTC, merged